/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AdminpanelRouteImport } from './routes/adminpanel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminpanelIndexRouteImport } from './routes/adminpanel.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as AdminpanelSystemsRouteImport } from './routes/adminpanel.systems'
import { Route as AdminpanelSocialRouteImport } from './routes/adminpanel.social'
import { Route as AdminpanelSlidesRouteImport } from './routes/adminpanel.slides'
import { Route as AdminpanelServicesRouteImport } from './routes/adminpanel.services'
import { Route as AdminpanelOffersRouteImport } from './routes/adminpanel.offers'
import { Route as AdminpanelNewsRouteImport } from './routes/adminpanel.news'
import { Route as AdminpanelClientsRouteImport } from './routes/adminpanel.clients'

const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpanelRoute = AdminpanelRouteImport.update({
  id: '/adminpanel',
  path: '/adminpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpanelIndexRoute = AdminpanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminpanelRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpanelSystemsRoute = AdminpanelSystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => AdminpanelRoute,
} as any)
const AdminpanelSocialRoute = AdminpanelSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminpanelRoute,
} as any)
const AdminpanelSlidesRoute = AdminpanelSlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => AdminpanelRoute,
} as any)
const AdminpanelServicesRoute = AdminpanelServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminpanelRoute,
} as any)
const AdminpanelOffersRoute = AdminpanelOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminpanelRoute,
} as any)
const AdminpanelNewsRoute = AdminpanelNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminpanelRoute,
} as any)
const AdminpanelClientsRoute = AdminpanelClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminpanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminpanel': typeof AdminpanelRouteWithChildren
  '/clients': typeof ClientsRoute
  '/systems': typeof SystemsRoute
  '/adminpanel/clients': typeof AdminpanelClientsRoute
  '/adminpanel/news': typeof AdminpanelNewsRoute
  '/adminpanel/offers': typeof AdminpanelOffersRoute
  '/adminpanel/services': typeof AdminpanelServicesRoute
  '/adminpanel/slides': typeof AdminpanelSlidesRoute
  '/adminpanel/social': typeof AdminpanelSocialRoute
  '/adminpanel/systems': typeof AdminpanelSystemsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/adminpanel/': typeof AdminpanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/systems': typeof SystemsRoute
  '/adminpanel/clients': typeof AdminpanelClientsRoute
  '/adminpanel/news': typeof AdminpanelNewsRoute
  '/adminpanel/offers': typeof AdminpanelOffersRoute
  '/adminpanel/services': typeof AdminpanelServicesRoute
  '/adminpanel/slides': typeof AdminpanelSlidesRoute
  '/adminpanel/social': typeof AdminpanelSocialRoute
  '/adminpanel/systems': typeof AdminpanelSystemsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/adminpanel': typeof AdminpanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminpanel': typeof AdminpanelRouteWithChildren
  '/clients': typeof ClientsRoute
  '/systems': typeof SystemsRoute
  '/adminpanel/clients': typeof AdminpanelClientsRoute
  '/adminpanel/news': typeof AdminpanelNewsRoute
  '/adminpanel/offers': typeof AdminpanelOffersRoute
  '/adminpanel/services': typeof AdminpanelServicesRoute
  '/adminpanel/slides': typeof AdminpanelSlidesRoute
  '/adminpanel/social': typeof AdminpanelSocialRoute
  '/adminpanel/systems': typeof AdminpanelSystemsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/adminpanel/': typeof AdminpanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminpanel'
    | '/clients'
    | '/systems'
    | '/adminpanel/clients'
    | '/adminpanel/news'
    | '/adminpanel/offers'
    | '/adminpanel/services'
    | '/adminpanel/slides'
    | '/adminpanel/social'
    | '/adminpanel/systems'
    | '/news/$slug'
    | '/adminpanel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/systems'
    | '/adminpanel/clients'
    | '/adminpanel/news'
    | '/adminpanel/offers'
    | '/adminpanel/services'
    | '/adminpanel/slides'
    | '/adminpanel/social'
    | '/adminpanel/systems'
    | '/news/$slug'
    | '/adminpanel'
  id:
    | '__root__'
    | '/'
    | '/adminpanel'
    | '/clients'
    | '/systems'
    | '/adminpanel/clients'
    | '/adminpanel/news'
    | '/adminpanel/offers'
    | '/adminpanel/services'
    | '/adminpanel/slides'
    | '/adminpanel/social'
    | '/adminpanel/systems'
    | '/news/$slug'
    | '/adminpanel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminpanelRoute: typeof AdminpanelRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  SystemsRoute: typeof SystemsRoute
  NewsSlugRoute: typeof NewsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpanel': {
      id: '/adminpanel'
      path: '/adminpanel'
      fullPath: '/adminpanel'
      preLoaderRoute: typeof AdminpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpanel/': {
      id: '/adminpanel/'
      path: '/'
      fullPath: '/adminpanel/'
      preLoaderRoute: typeof AdminpanelIndexRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpanel/systems': {
      id: '/adminpanel/systems'
      path: '/systems'
      fullPath: '/adminpanel/systems'
      preLoaderRoute: typeof AdminpanelSystemsRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/adminpanel/social': {
      id: '/adminpanel/social'
      path: '/social'
      fullPath: '/adminpanel/social'
      preLoaderRoute: typeof AdminpanelSocialRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/adminpanel/slides': {
      id: '/adminpanel/slides'
      path: '/slides'
      fullPath: '/adminpanel/slides'
      preLoaderRoute: typeof AdminpanelSlidesRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/adminpanel/services': {
      id: '/adminpanel/services'
      path: '/services'
      fullPath: '/adminpanel/services'
      preLoaderRoute: typeof AdminpanelServicesRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/adminpanel/offers': {
      id: '/adminpanel/offers'
      path: '/offers'
      fullPath: '/adminpanel/offers'
      preLoaderRoute: typeof AdminpanelOffersRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/adminpanel/news': {
      id: '/adminpanel/news'
      path: '/news'
      fullPath: '/adminpanel/news'
      preLoaderRoute: typeof AdminpanelNewsRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/adminpanel/clients': {
      id: '/adminpanel/clients'
      path: '/clients'
      fullPath: '/adminpanel/clients'
      preLoaderRoute: typeof AdminpanelClientsRouteImport
      parentRoute: typeof AdminpanelRoute
    }
  }
}

interface AdminpanelRouteChildren {
  AdminpanelClientsRoute: typeof AdminpanelClientsRoute
  AdminpanelNewsRoute: typeof AdminpanelNewsRoute
  AdminpanelOffersRoute: typeof AdminpanelOffersRoute
  AdminpanelServicesRoute: typeof AdminpanelServicesRoute
  AdminpanelSlidesRoute: typeof AdminpanelSlidesRoute
  AdminpanelSocialRoute: typeof AdminpanelSocialRoute
  AdminpanelSystemsRoute: typeof AdminpanelSystemsRoute
  AdminpanelIndexRoute: typeof AdminpanelIndexRoute
}

const AdminpanelRouteChildren: AdminpanelRouteChildren = {
  AdminpanelClientsRoute: AdminpanelClientsRoute,
  AdminpanelNewsRoute: AdminpanelNewsRoute,
  AdminpanelOffersRoute: AdminpanelOffersRoute,
  AdminpanelServicesRoute: AdminpanelServicesRoute,
  AdminpanelSlidesRoute: AdminpanelSlidesRoute,
  AdminpanelSocialRoute: AdminpanelSocialRoute,
  AdminpanelSystemsRoute: AdminpanelSystemsRoute,
  AdminpanelIndexRoute: AdminpanelIndexRoute,
}

const AdminpanelRouteWithChildren = AdminpanelRoute._addFileChildren(
  AdminpanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminpanelRoute: AdminpanelRouteWithChildren,
  ClientsRoute: ClientsRoute,
  SystemsRoute: SystemsRoute,
  NewsSlugRoute: NewsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
